services:
  - type: web
    name: orf-atc-sim-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        value: "*"
      - key: OPENAI_TRANSCRIBE_MODEL
        value: gpt-4o-mini-transcribe
      - key: OPENAI_TTS_MODEL
        value: gpt-4o-mini-tts
